//console.log(Math.random());
console.log(null !== 2);
console.log(!!true);
console.log(!!false);
console.log(!!-1);
console.log(!!0);
console.log(!!1);
console.log(!!2);
console.log(!!null);
console.log(!!undefined);